title:            Michael Allar
description:      Unreal Engine 4 Specialized Engineer that does Other Things too
disqus_shortname: allarsblog
reading_time:     true
words_per_minute: 175
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:  http://allarsblog.com

# Owner/author information
owner:
  name:           Michael Allar
  avatar:         avatar.jpg
  bio:            "Professional game developer working with Unreal Engine 3 and 4 located in the Los Angeles area."
  email:          allar@michaelallar.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        michaelallar
  #facebook:       awesomeallar
  github:         allar
  #stackexchange:  
  linkedin:       allar
  #instagram:      
  #flickr:         
  #tumblr:         
  # google plus id, include the '+', eg +mmistakes
  #google_plus:    +yourid

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-55007129-1
google_verify:  6MIC1dP3EPSEtoKAnJayxa8Tcnfo065FIzE928vMWa4
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]