# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Allar
tagline:          'A Jekyll theme'
description:      "<a href=\"https://twitter.com/michaelallar\" target=\"_blank\">@michaelallar</a>'s random, generally technical, writings about the development of things."
url:              http://allarsblog.com

author:
  name:           'Michael Allar'
  url:            https://twitter.com/michaelallar

paginate:         5

# Custom vars
version:          2.0.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      disqusidentifier: home_change_me
      comments: true
      
gems:
  - jekyll-sitemap