# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Allar
tagline:          'A Jekyll theme'
description:      "<a href=\"https://twitter.com/michaelallar\" target=\"_blank\">@michaelallar</a>'s random writings about the development of things."
url:              http://michaelallar.com

author:
  name:           'Michael Allar'
  url:            https://twitter.com/michaelallar

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde